export const GET_ALL_RECORD_LIST_IN_PROGRESS =
  "GET_ALL_RECORD_LIST_IN_PROGRESS";
export const GET_ALL_RECORD_LIST_ON_SUCCESS = "GET_ALL_RECORD_LIST_ON_SUCCESS";
export const GET_ALL_RECORD_LIST_ON_FAILED = "GET_ALL_RECORD_LIST_ON_FAILED";

// Get by List
export const GET_CURRENCY_LIST_IN_PROGRESS = "GET_CURRENCY_LIST_IN_PROGRESS";
export const GET_CURRENCY_LIST_ON_SUCCESS = "GET_CURRENCY_LIST_ON_SUCCESS";
export const GET_CURRENCY_LIST_ON_FAILED = "GET_CURRENCY_LIST_ON_FAILED";
